vac/urls.py
from django.urls import path
from .views import *
from .apps import VacConfig


app_name = VacConfig.name

urlpatterns = [
    path('patient/create/', PatientCreateView.as_view(), name='patient_create'),
]

vaccination1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls as auth_urls
from rest_framework.routers import DefaultRouter
from usermanager.views import HomeView, UserUpdateView


from usermanager.viewsets import UserViewset, CentreViewset, DistrictViewset
from vac.viewsets import *


router = DefaultRouter()
router.register('users', UserViewset)
router.register('centres', CentreViewset)
router.register('districts', DistrictViewset)
router.register('patients', PatientViewset)
router.register('vaccins', VaccinViewset)
router.register('vaccinations', VaccinationViewset)
router.register('testseros', TestSeroViewset)
router.register('enquetes', EnquetViewset)


urlpatterns = [
    path('api/v1/', include(router.get_urls())),
    path('rest/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('', include(auth_urls)),
    path('', HomeView.as_view(), name='home'),
    path('update-profile/<int:pk>', UserUpdateView.as_view(), name='update_profile'),
    path('vaccination/', include('vac.urls', namespace='vac')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VAccination Covid</title>
</head>
<body>

<fieldset>
    <legend>{{ user.centre }}</legend>
    <ul>
        <li>
            <a href="{% url 'home' %}">Acceuil</a>
        </li>
        <li>
            <a href="{% url 'logout' %}">Se deconnecter</a>
        </li>
        <li>
            <a href="{% url 'update_profile' pk=user.pk %}">Profile</a>
        </li>
        <li>
            <a href="{% url 'password_change' %}">Modifier mon mot de passe</a>
        </li>
        <li>
            <a href="{% url 'vac:patient_create' %}">Ajouter un patient</a>
        </li>
    </ul>
</fieldset>
    <ul>
        {% if user.role == ADMIN %}
        <li>Menu Admin</li>
        {% endif %}
        {% if user.role == MEDECIN %}
        <li>Menu Medecin</li>
        {% endif %}
        {% if user.role == ENREGISTREUR %}
        <li>Menu Enregistreur</li>
        {% endif %}
        {% if user.role == OBSERVATEUR %}
        <li>Menu Observateur</li>
        {% endif %}
        {% if user.role == CHEFCENTRE %}
        <li>Menu Chef de centre</li>
        {% endif %}
    </ul>
    <span></span>
    {% block content %}

    {% endblock %}

    {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
    {% endfor %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Bienvenue sur votre dashboard, {{ user.username }} </h1>
{% endblock %}